// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKrlCP72fD5Oo_MS66A-HhIm1aaWCArY',
    appId: '1:880138699529:web:edd78e64d432a523acc9d8',
    messagingSenderId: '880138699529',
    projectId: 'wticabs-a98bb',
    authDomain: 'wticabs-a98bb.firebaseapp.com',
    storageBucket: 'wticabs-a98bb.firebasestorage.app',
    measurementId: 'G-TBRMH1ZYB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlm4H5v-hSc61SMRm-Or54Gk-W82V3lPU',
    appId: '1:880138699529:android:914879337a647e73acc9d8',
    messagingSenderId: '880138699529',
    projectId: 'wticabs-a98bb',
    storageBucket: 'wticabs-a98bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeB-dvxw6ZEfHAf1RaGLHsXqNc5LTPRGo',
    appId: '1:880138699529:ios:d15afed9cc97e6dfacc9d8',
    messagingSenderId: '880138699529',
    projectId: 'wticabs-a98bb',
    storageBucket: 'wticabs-a98bb.firebasestorage.app',
    androidClientId: '880138699529-let5c55aavfhkch0nlgddoe8115o1juc.apps.googleusercontent.com',
    iosClientId: '880138699529-sk8hpragkimnim2g1s9ma48b6je2ov97.apps.googleusercontent.com',
    iosBundleId: 'com.wti.user.wtiCabsUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeB-dvxw6ZEfHAf1RaGLHsXqNc5LTPRGo',
    appId: '1:880138699529:ios:a984d8e276a8a5a3acc9d8',
    messagingSenderId: '880138699529',
    projectId: 'wticabs-a98bb',
    storageBucket: 'wticabs-a98bb.firebasestorage.app',
    androidClientId: '880138699529-let5c55aavfhkch0nlgddoe8115o1juc.apps.googleusercontent.com',
    iosClientId: '880138699529-e50rorhn6s3rt6d9n8o7m5jvb13c0575.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtiCabsUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOKrlCP72fD5Oo_MS66A-HhIm1aaWCArY',
    appId: '1:880138699529:web:fb70345f85a5c062acc9d8',
    messagingSenderId: '880138699529',
    projectId: 'wticabs-a98bb',
    authDomain: 'wticabs-a98bb.firebaseapp.com',
    storageBucket: 'wticabs-a98bb.firebasestorage.app',
    measurementId: 'G-PCVM6DCP75',
  );

}