// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0VaIu47ZmQfwfFPhr1asYh2Ux_DfydM',
    appId: '1:350350132251:web:f96ce9cc7778fdc8a3a4be',
    messagingSenderId: '350350132251',
    projectId: 'wticabsuserb2c',
    authDomain: 'wticabsuserb2c.firebaseapp.com',
    storageBucket: 'wticabsuserb2c.firebasestorage.app',
    measurementId: 'G-5KVKTK0M8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ersFUK_sIYny13OIybnElH9y0vxLL40',
    appId: '1:350350132251:android:97d1945a8ee9c1dca3a4be',
    messagingSenderId: '350350132251',
    projectId: 'wticabsuserb2c',
    storageBucket: 'wticabsuserb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRU3VVcNJFU97NFbMT8kaf2loHxBxfhM8',
    appId: '1:350350132251:ios:618d5f26dcf980cda3a4be',
    messagingSenderId: '350350132251',
    projectId: 'wticabsuserb2c',
    storageBucket: 'wticabsuserb2c.firebasestorage.app',
    iosClientId: '350350132251-oqnm5kahh5daerh0sob5rm49voeu2mpa.apps.googleusercontent.com',
    iosBundleId: 'com.wti.user.wtiCabsUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRU3VVcNJFU97NFbMT8kaf2loHxBxfhM8',
    appId: '1:350350132251:ios:1acbbabe68b39387a3a4be',
    messagingSenderId: '350350132251',
    projectId: 'wticabsuserb2c',
    storageBucket: 'wticabsuserb2c.firebasestorage.app',
    iosClientId: '350350132251-r6l30e84f570g5ggp9hht1phq3n1lflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtiCabsUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-0VaIu47ZmQfwfFPhr1asYh2Ux_DfydM',
    appId: '1:350350132251:web:9af5d5619623182ea3a4be',
    messagingSenderId: '350350132251',
    projectId: 'wticabsuserb2c',
    authDomain: 'wticabsuserb2c.firebaseapp.com',
    storageBucket: 'wticabsuserb2c.firebasestorage.app',
    measurementId: 'G-J3ET8LP5BG',
  );

}