// utils/currency_utils.dart
class CurrencyUtils {
  static final List<Map<String, String>> currencies = [
    {"code": "AED", "symbol": "د.إ", "name": "United Arab Emirates Dirham"},
    {"code": "AFN", "symbol": "؋", "name": "Afghan Afghani"},
    {"code": "ALL", "symbol": "L", "name": "Albanian Lek"},
    {"code": "AMD", "symbol": "֏", "name": "Armenian Dram"},
    {"code": "ANG", "symbol": "ƒ", "name": "Netherlands Antillean Guilder"},
    {"code": "AOA", "symbol": "Kz", "name": "Angolan Kwanza"},
    {"code": "ARS", "symbol": "\$", "name": "Argentine Peso"},
    {"code": "AUD", "symbol": "\$", "name": "Australian Dollar"},
    {"code": "AWG", "symbol": "ƒ", "name": "Aruban Florin"},
    {"code": "AZN", "symbol": "₼", "name": "Azerbaijani Manat"},
    {"code": "BAM", "symbol": "KM", "name": "Bosnia and Herzegovina Convertible Mark"},
    {"code": "BBD", "symbol": "\$", "name": "Barbadian Dollar"},
    {"code": "BDT", "symbol": "৳", "name": "Bangladeshi Taka"},
    {"code": "BGN", "symbol": "лв", "name": "Bulgarian Lev"},
    {"code": "BHD", "symbol": ".د.ب", "name": "Bahraini Dinar"},
    {"code": "BIF", "symbol": "FBu", "name": "Burundian Franc"},
    {"code": "BMD", "symbol": "\$", "name": "Bermudian Dollar"},
    {"code": "BND", "symbol": "\$", "name": "Brunei Dollar"},
    {"code": "BOB", "symbol": "Bs.", "name": "Bolivian Boliviano"},
    {"code": "BRL", "symbol": "R\$", "name": "Brazilian Real"},
    {"code": "BSD", "symbol": "\$", "name": "Bahamian Dollar"},
    {"code": "BTN", "symbol": "Nu.", "name": "Bhutanese Ngultrum"},
    {"code": "BWP", "symbol": "P", "name": "Botswana Pula"},
    {"code": "BYN", "symbol": "Br", "name": "Belarusian Ruble"},
    {"code": "BZD", "symbol": "BZ\$", "name": "Belize Dollar"},
    {"code": "CAD", "symbol": "\$", "name": "Canadian Dollar"},
    {"code": "CDF", "symbol": "FC", "name": "Congolese Franc"},
    {"code": "CHF", "symbol": "CHF", "name": "Swiss Franc"},
    {"code": "CLP", "symbol": "\$", "name": "Chilean Peso"},
    {"code": "CNY", "symbol": "¥", "name": "Chinese Yuan"},
    {"code": "COP", "symbol": "\$", "name": "Colombian Peso"},
    {"code": "CRC", "symbol": "₡", "name": "Costa Rican Colón"},
    {"code": "CUP", "symbol": "₱", "name": "Cuban Peso"},
    {"code": "CZK", "symbol": "Kč", "name": "Czech Koruna"},
    {"code": "DJF", "symbol": "Fdj", "name": "Djiboutian Franc"},
    {"code": "DKK", "symbol": "kr", "name": "Danish Krone"},
    {"code": "DOP", "symbol": "RD\$", "name": "Dominican Peso"},
    {"code": "DZD", "symbol": "دج", "name": "Algerian Dinar"},
    {"code": "EGP", "symbol": "£", "name": "Egyptian Pound"},
    {"code": "ETB", "symbol": "Br", "name": "Ethiopian Birr"},
    {"code": "EUR", "symbol": "€", "name": "Euro"},
    {"code": "FJD", "symbol": "\$", "name": "Fijian Dollar"},
    {"code": "GBP", "symbol": "£", "name": "British Pound"},
    {"code": "GEL", "symbol": "₾", "name": "Georgian Lari"},
    {"code": "GHS", "symbol": "₵", "name": "Ghanaian Cedi"},
    {"code": "GTQ", "symbol": "Q", "name": "Guatemalan Quetzal"},
    {"code": "HKD", "symbol": "HK\$", "name": "Hong Kong Dollar"},
    {"code": "HNL", "symbol": "L", "name": "Honduran Lempira"},
    {"code": "HRK", "symbol": "kn", "name": "Croatian Kuna"},
    {"code": "HUF", "symbol": "Ft", "name": "Hungarian Forint"},
    {"code": "IDR", "symbol": "Rp", "name": "Indonesian Rupiah"},
    {"code": "ILS", "symbol": "₪", "name": "Israeli Shekel"},
    {"code": "INR", "symbol": "₹", "name": "Indian Rupee"},
    {"code": "IQD", "symbol": "ع.د", "name": "Iraqi Dinar"},
    {"code": "IRR", "symbol": "﷼", "name": "Iranian Rial"},
    {"code": "ISK", "symbol": "kr", "name": "Icelandic Krona"},
    {"code": "JMD", "symbol": "J\$", "name": "Jamaican Dollar"},
    {"code": "JOD", "symbol": "د.ا", "name": "Jordanian Dinar"},
    {"code": "JPY", "symbol": "¥", "name": "Japanese Yen"},
    {"code": "KES", "symbol": "KSh", "name": "Kenyan Shilling"},
    {"code": "KGS", "symbol": "лв", "name": "Kyrgyzstani Som"},
    {"code": "KHR", "symbol": "៛", "name": "Cambodian Riel"},
    {"code": "KPW", "symbol": "₩", "name": "North Korean Won"},
    {"code": "KRW", "symbol": "₩", "name": "South Korean Won"},
    {"code": "KWD", "symbol": "د.ك", "name": "Kuwaiti Dinar"},
    {"code": "KZT", "symbol": "₸", "name": "Kazakhstani Tenge"},
    {"code": "LAK", "symbol": "₭", "name": "Lao Kip"},
    {"code": "LBP", "symbol": "ل.ل", "name": "Lebanese Pound"},
    {"code": "LKR", "symbol": "Rs", "name": "Sri Lankan Rupee"},
    {"code": "MAD", "symbol": "MAD", "name": "Moroccan Dirham"},
    {"code": "MDL", "symbol": "L", "name": "Moldovan Leu"},
    {"code": "MMK", "symbol": "K", "name": "Myanmar Kyat"},
    {"code": "MNT", "symbol": "₮", "name": "Mongolian Tögrög"},
    {"code": "MUR", "symbol": "₨", "name": "Mauritian Rupee"},
    {"code": "MXN", "symbol": "\$", "name": "Mexican Peso"},
    {"code": "MYR", "symbol": "RM", "name": "Malaysian Ringgit"},
    {"code": "NAD", "symbol": "N\$", "name": "Namibian Dollar"},
    {"code": "NGN", "symbol": "₦", "name": "Nigerian Naira"},
    {"code": "NOK", "symbol": "kr", "name": "Norwegian Krone"},
    {"code": "NPR", "symbol": "₨", "name": "Nepalese Rupee"},
    {"code": "NZD", "symbol": "\$", "name": "New Zealand Dollar"},
    {"code": "OMR", "symbol": "﷼", "name": "Omani Rial"},
    {"code": "PEN", "symbol": "S/.", "name": "Peruvian Sol"},
    {"code": "PHP", "symbol": "₱", "name": "Philippine Peso"},
    {"code": "PKR", "symbol": "₨", "name": "Pakistani Rupee"},
    {"code": "PLN", "symbol": "zł", "name": "Polish Zloty"},
    {"code": "QAR", "symbol": "﷼", "name": "Qatari Riyal"},
    {"code": "RON", "symbol": "lei", "name": "Romanian Leu"},
    {"code": "RUB", "symbol": "₽", "name": "Russian Ruble"},
    {"code": "SAR", "symbol": "ر.س", "name": "Saudi Riyal"},
    {"code": "SEK", "symbol": "kr", "name": "Swedish Krona"},
    {"code": "SGD", "symbol": "\$", "name": "Singapore Dollar"},
    {"code": "THB", "symbol": "฿", "name": "Thai Baht"},
    {"code": "TRY", "symbol": "₺", "name": "Turkish Lira"},
    {"code": "TWD", "symbol": "NT\$", "name": "New Taiwan Dollar"},
    {"code": "TZS", "symbol": "TSh", "name": "Tanzanian Shilling"},
    {"code": "UAH", "symbol": "₴", "name": "Ukrainian Hryvnia"},
    {"code": "UGX", "symbol": "USh", "name": "Ugandan Shilling"},
    {"code": "USD", "symbol": "\$", "name": "US Dollar"},
    {"code": "UYU", "symbol": "\$U", "name": "Uruguayan Peso"},
    {"code": "UZS", "symbol": "лв", "name": "Uzbekistani Som"},
    {"code": "VND", "symbol": "₫", "name": "Vietnamese Dong"},
    {"code": "YER", "symbol": "﷼", "name": "Yemeni Rial"},
    {"code": "ZAR", "symbol": "R", "name": "South African Rand"},
    {"code": "ZMW", "symbol": "ZK", "name": "Zambian Kwacha"},
  ];
}
